import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import Providers from "../utils/AuthProvider";
import Navbar from "../commonComponents/navbar/Navbar";
import Footer from "../commonComponents/footer/Footer";
import ToastProvider from "../components/toast/ToastProvider";
import { FirmsProvider } from "../context/FirmsContext"; // <-- import FirmsProvider

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["700"], // for headings
  variable: "--font-poppins",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500"], // for body
  variable: "--font-inter",
});

export const metadata = {
  title: "Prop Firm Flow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inter.variable} antialiased`}>
        <Providers>
          <FirmsProvider> {/* <-- wrap your app with FirmsProvider */}
            <ToastProvider />
            <Navbar />
            <main className="pt-[124px] min-h-screen">
              {children}
            </main>
            <Footer />
          </FirmsProvider>
        </Providers>
      </body>
    </html>
  );
}
